version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=tcc_project
      - DB_USER=projetotcc
      - DB_PASS=tcc_2023
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tcc_2023
      MYSQL_DATABASE: tcc_project
      MYSQL_USER: projetotcc
      MYSQL_PASSWORD:: tcc_2023
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
