version: '3.3'
services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=tcc_project
      - DB_USER=projetotcc
      - DB_PASS=tcc2023
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=city_database
    depends_on:
      - db
      - mongo
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tcc2023
      MYSQL_DATABASE: tcc_project
      MYSQL_USER: projetotcc
      MYSQL_PASSWORD: tcc2023
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tcc-base-dados.sql:/docker-entrypoint-initdb.d/base-dados.sql
    restart: always

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mysql_data:
  mongo_data:
