services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=tcc_project
      - DB_USER=projetotcc
      - DB_PASS=tcc_2023
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: tcc_2023
      MYSQL_DATABASE: tcc_project
      MYSQL_USER: projetotcc
      MYSQL_PASSWORD: tcc_2023
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tcc-base-dados.sql:/docker-entrypoint-initdb.d/base-dados.sql
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
